Map<String, String> animalDict = {
  'bear': 'images/animals/bear.png',
  'bore': 'images/animals/bore.png',
  'cat': 'images/animals/cat.png',
  'chick': 'images/animals/chick.png',
  'cow': 'images/animals/cow.png',
  'dog': 'images/animals/dog.png',
  'fox': 'images/animals/fox.png',
  'lion': 'images/animals/lion.png',
  'monkey': 'images/animals/monkey.png',
  'mouse': 'images/animals/mouse.png',
  'pig': 'images/animals/pig.png',
  'racoon': 'images/animals/racoon.png',
  'squirrel': 'images/animals/squirrel.png',
  'tiger': 'images/animals/tiger.png',
};